apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-redis-auth
  namespace: personal-ai
spec:
  secretTargetRef:
  - parameter: host
    name: app-secrets
    key: REDIS_URL
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-rabbitmq-auth
  namespace: personal-ai
spec:
  secretTargetRef:
  - parameter: host
    name: app-secrets
    key: CELERY_BROKER_URL
---
# Scaler para el Worker de la App (RabbitMQ/Celery)
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: celery-worker-scaler
  namespace: personal-ai
spec:
  scaleTargetRef:
    name: worker-deployment
  minReplicaCount: 0
  maxReplicaCount: 1
  triggers:
  - type: rabbitmq
    metadata:
      queueName: ingest_q
      queueLength: "5"
    authenticationRef:
      name: keda-rabbitmq-auth # Asumo que este auth existe para RabbitMQ