"""fase 9 ingesta masiva y batch tracking

Revision ID: 01744627c136
Revises: default_chat_feedback
Create Date: 2026-04-30 15:25:25.799095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle
import src.providers.database.models

# revision identifiers, used by Alembic.
revision = '01744627c136'
down_revision = 'default_chat_feedback'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Comentado porque ya se ejecutaron en el intento fallido anterior (Oracle DDL no es transaccional)
    # op.create_table('ingestion_batches',
    # sa.Column('batch_id', src.providers.database.models.GUID(), nullable=False),
    # sa.Column('user_id', sa.String(length=255), nullable=True),
    # sa.Column('status', sa.String(length=50), nullable=False),
    # sa.Column('total_files', sa.Integer(), nullable=False),
    # sa.Column('doc_ids', src.providers.database.models.JSONText(), nullable=True),
    # sa.Column('errors', src.providers.database.models.JSONText(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('batch_id')
    # )
    # op.create_index(op.f('ix_ingestion_batches_user_id'), 'ingestion_batches', ['user_id'], unique=False)
    # op.create_table('ingestion_sync_state',
    # sa.Column('id', src.providers.database.models.GUID(), nullable=False),
    # sa.Column('user_id', sa.String(length=255), nullable=False),
    # sa.Column('source_type', sa.String(length=50), nullable=False),
    # sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    # sa.Column('status', sa.String(length=50), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_ingestion_sync_state_user_id'), 'ingestion_sync_state', ['user_id'], unique=False)
    
    # En Oracle, no se puede borrar un índice que respalda una PK/UK directamente. 
    # Al borrar la tabla 'upsertion_record' más abajo, el índice se borrará automáticamente.
    # op.drop_index('uix_key_namespace', table_name='upsertion_record')
    
    op.drop_table('upsertion_record')
    op.drop_table('dbtools$execution_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbtools$execution_history',
    sa.Column('id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('hash', sa.CLOB(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_on', oracle.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_on', oracle.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('statement', sa.CLOB(), nullable=True),
    sa.Column('times', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('id', name='dbtools$execution_history_pk'),
    oracle_tablespace='DATA'
    )
    op.create_table('upsertion_record',
    sa.Column('uuid', sa.VARCHAR(length=255), nullable=False),
    sa.Column('key', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('namespace', sa.VARCHAR(length=255), nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', sa.DOUBLE_PRECISION(), nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='sys_c0030267'),
    oracle_tablespace='DATA'
    )
    op.create_index('uix_key_namespace', 'upsertion_record', ['key', 'namespace'], unique=True)
    op.drop_index(op.f('ix_ingestion_sync_state_user_id'), table_name='ingestion_sync_state')
    op.drop_table('ingestion_sync_state')
    op.drop_index(op.f('ix_ingestion_batches_user_id'), table_name='ingestion_batches')
    op.drop_table('ingestion_batches')
    # ### end Alembic commands ###
