"""agregar integraciones para la automatizacion de obtener las tareas

Revision ID: 0ebafca9fb18
Revises: 01744627c136
Create Date: 2026-04-30 17:11:18.133691

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import src.providers.database.models


# revision identifiers, used by Alembic.
revision = '0ebafca9fb18'
down_revision = '01744627c136'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_integrations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=True),
    sa.Column('source_id', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_integrations_user_id'), 'user_integrations', ['user_id'], unique=False)
    # op.drop_index('uix_key_namespace', table_name='upsertion_record')
    # op.drop_table('upsertion_record')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('upsertion_record',
    # sa.Column('uuid', sa.VARCHAR(length=255), nullable=False),
    # sa.Column('key', sa.VARCHAR(length=4000), nullable=True),
    # sa.Column('namespace', sa.VARCHAR(length=255), nullable=False),
    # sa.Column('group_id', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('updated_at', sa.DOUBLE_PRECISION(), nullable=True),
    # sa.PrimaryKeyConstraint('uuid', name='sys_c0030414'),
    # oracle_tablespace='DATA'
    # )
    # op.create_index('uix_key_namespace', 'upsertion_record', ['key', 'namespace'], unique=True)
    op.drop_index(op.f('ix_user_integrations_user_id'), table_name='user_integrations')
    op.drop_table('user_integrations')
    # ### end Alembic commands ###
