"""fase 9 notion sync metadata tabla

Revision ID: 8e451bf33ada
Revises: 0ebafca9fb18
Create Date: 2026-05-02 15:21:22.178678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e451bf33ada'
down_revision = '0ebafca9fb18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion_sync_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('notion_id', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(length=255), nullable=True),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('last_edited_time', sa.DateTime(), nullable=True),
    sa.Column('file_hash', sa.String(length=256), nullable=True),
    sa.Column('is_archived', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notion_sync_metadata_notion_id'), 'notion_sync_metadata', ['notion_id'], unique=False)
    op.create_index(op.f('ix_notion_sync_metadata_user_id'), 'notion_sync_metadata', ['user_id'], unique=False)
    # op.drop_index('uix_key_namespace', table_name='upsertion_record')  # Tabla de LangChain, no tocar
    # op.drop_table('upsertion_record')  # Tabla de LangChain, no tocar
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upsertion_record',
    sa.Column('uuid', sa.VARCHAR(length=255), nullable=False),
    sa.Column('key', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('namespace', sa.VARCHAR(length=255), nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', sa.DOUBLE_PRECISION(), nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='sys_c0030414'),
    oracle_tablespace='DATA'
    )
    # op.create_table('upsertion_record', ...)  # Tabla de LangChain, no tocar
    # op.create_index('uix_key_namespace', ...)  # Tabla de LangChain, no tocar
    op.drop_index(op.f('ix_notion_sync_metadata_user_id'), table_name='notion_sync_metadata')
    op.drop_index(op.f('ix_notion_sync_metadata_notion_id'), table_name='notion_sync_metadata')
    op.drop_table('notion_sync_metadata')
    # ### end Alembic commands ###
