"""fase 9 reporte de ingesta

Revision ID: b5a341696e38
Revises: 8e451bf33ada
Create Date: 2026-05-12 15:09:21.688325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a341696e38'
down_revision = '8e451bf33ada'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('uix_key_namespace', table_name='upsertion_record')  # Fails in Oracle (ORA-02429), table drop will handle it.
    op.drop_table('upsertion_record')
    op.add_column('ingestion_jobs', sa.Column('report', sa.Text(), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('chunks_count', sa.Integer(), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('strategy', sa.String(length=50), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('processing_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'processing_time')
    op.drop_column('ingestion_jobs', 'strategy')
    op.drop_column('ingestion_jobs', 'chunks_count')
    op.drop_column('ingestion_jobs', 'report')
    op.create_table('upsertion_record',
    sa.Column('uuid', sa.VARCHAR(length=255), nullable=False),
    sa.Column('key', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('namespace', sa.VARCHAR(length=255), nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', sa.DOUBLE_PRECISION(), nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='sys_c0030414'),
    oracle_tablespace='DATA'
    )
    op.create_index('uix_key_namespace', 'upsertion_record', ['key', 'namespace'], unique=True)
    # ### end Alembic commands ###
