services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8001:8000" # Mapeamos a 8001 para no chocar con Chroma si corre nativo
    env_file: ../.env.local
    depends_on:
      chromadb:
        condition: service_healthy
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb-server
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/app/chroma/chroma-data
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  chroma-data:
