name: Develop CI - Local Testing

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Obtener secretos de Infisical
      uses: Infisical/secrets-action@v1.0.8
      with:
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          env-slug: "prod"
          project-slug: "bmo-ai-assistant-qd7o"
          secret-path: "/"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/local.txt
    
    # Nota: Testcontainers levantará Docker por su cuenta en background
    - name: Run Unit
      env:
        # Variables fakes que necesitan los clientes para instanciarse (aunque el factory esté mockeado)
        GOOGLE_API_KEY: "fake_google_key"
        OPENAI_API_KEY: "fake_openai_key"
        OPENWEATHERMAP_API_KEY: "fake_weather_key"
      run: |
        pytest src/tests/unit